from django.shortcuts import render, redirect
from django.http import HttpResponse
from transformers import GPT2Tokenizer
from django.urls.base import reverse_lazy
import torch


def get_sympton(sickness):
    model = torch.load("C:\cs\sympton_checker\source\SmallMedLM.pt")
    device = torch.device("cuda")
    tokenizer = GPT2Tokenizer.from_pretrained("distilgpt2")

    input_str = sickness #what we input
    input_ids = tokenizer.encode(input_str, return_tensors = 'pt').to(device) #need to change to langauge for AI, hence using 'pt'
    
    output = model.generate(
    input_ids,
    max_length = 40,
    num_return_sequences = 1,
    do_sample = True,
    top_k = 8,
    top_p = 0.95, #neural network
    temperature = 0.5, #bullshitting skills
    repetition_penalty = 1.2,
    pad_token_id = tokenizer.eos_token_id) #some ai settings and shits for its reposonse

    decoded_output = tokenizer.decode(output[0], skip_special_tokens = True) #translate to human language after output is generated, since it's generated by AI it's in their lang (numbers), so we need to translate to our language to understand, that's why tokenizer is used. 

    return decoded_output

def index(request):
    result = None

    if request.method == "POST":
        sickness = request.POST["sickness"] #post is a dictionary so need []
        
        if sickness != "":
            result = get_sympton(sickness)

    return render(request,"main/index.html",{'result': result})

def welcome(request):
    return render(request,"main/welcome.html")

def blank(request):
    url = reverse_lazy("main:welcome") #是找views的name
    return redirect(url)
